test_heap_min: test_heap_min.o heap_min.o
	gcc -o test_heap_min test_heap_min.o heap_min.o
	
test_heap_min.o: test_heap_min.c heap_min.h
	gcc -c test_heap_min.c
	
heap_min.o: heap_min.c
	gcc -c heap_min.c	
